workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get Flutter packages
        script: |
          cd alazkar
          flutter pub get
      - name: Build Android APK
        script: |
          cd alazkar
          flutter build apk --debug --flavor dev --android-skip-build-dependency-validation
    artifacts:
      - alazkar/build/app/outputs/flutter-apk/**/*.apk
      - alazkar/build/app/outputs/apk/**/*.apk
